repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-yaml
        exclude: 'deploy/helm'
    -   id: mixed-line-ending
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
